#+begin_html
<p align="center">
  <a href="https://github.com/sponsors/d12frosted"><img alt="Sponsor" src="https://img.shields.io/badge/Sponsor-d12frosted-pink?logo=githubsponsors&logoColor=white"/></a>
</p>
#+end_html

* =emacs-addiction-mode=
:PROPERTIES:
:ID:                     b2df1b4f-7051-4a65-ad19-29c7d1f8d23c
:END:

Keybinding for killing Emacs is an awful joke. It should not exist in the first
place. If I wanted to exit Emacs, I would call a doctor.

=emacs-addiction-mode= comes into play. Quit killing Emacs. Raise your addiction
level and be happy about it.

Call =emacs-addiction-mode= to turn it locally. Call
=global-emacs-addiction-mode= to turn it globally. Set your
=emacs-addiction-level= and conquer this Universe.

Available levels:

- =neophyte= - your addiction is new, so you are still unsure. You will be
  prompted if you really want to quit Emacs.
- =sane= - you are a sane person. On any attempt to kill Emacs you will be
  brought straight to the psychotherapist.
- =brian= - you 'always look on the bright side of life'. So you don't need to
  kill Emacs anymore.

** Installation
:PROPERTIES:
:ID:                     c276874b-7f85-4ee9-8525-457a3a90bc4e
:END:

*** MELPA
:PROPERTIES:
:ID:                     d16cfdf7-8a85-48f7-88b3-070186603941
:END:

This package is not yet available on MELPA.

*** Quelpa
:PROPERTIES:
:ID:                     45228272-e633-4290-9b8c-88826be0b11e
:END:

#+BEGIN_SRC emacs-lisp
  (quelpa '(emacs-addiction-mode :repo "d12frosted/emacs-addiction-mode" :fetcher github))
#+END_SRC

*** straight.el
:PROPERTIES:
:ID:                     2beccee5-417a-4053-8275-217f41dedcca
:END:

#+begin_src emacs-lisp
  (straight-use-package
   '(emacs-addiction-mode :type git :host github :repo "d12frosted/emacs-addiction-mode"))
#+end_src

In case you have [[https://github.com/raxod502/straight.el/#integration-with-use-package][integration]] with [[https://github.com/jwiegley/use-package][use-package]]:

#+begin_src emacs-lisp
  (use-package emacs-addiction-mode
    :straight (emacs-addiction-mode
               :type git
               :host github
               :repo "d12frosted/emacs-addiction-mode"))
#+end_src

** Example
:PROPERTIES:
:ID:                     51e21205-6e47-4466-a5fc-35a2e7dccd50
:END:

#+BEGIN_SRC emacs-lisp
  (require 'emacs-addiction-mode)
  (global-emacs-addiction-mode)
  (setq emacs-addiction-level 'brian)
#+END_SRC

** Contributing
:PROPERTIES:
:ID:                     5dd81ea0-4c42-42b9-a574-a2a260cb663d
:END:

Everyone is welcome to contribute to =emacs-addiction-mode= project. Feature
requests, proposals, issue reports, documentation improvements, code patches -
just to name few things that the project can gain from.

Happy hacking!

* Support

If you enjoy this project, you can support its development via [[https://github.com/sponsors/d12frosted][GitHub Sponsors]] or [[https://www.patreon.com/d12frosted][Patreon]].
